using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;

namespace Microsoft.R9.Extensions.MetricGenerator
{
    public partial class MetricGenerator
    {
        internal class Emitter
        {
            private readonly Stack<StringBuilder> _builders = new();
            private readonly string _fieldName = "_meter";

            public string EmitGenevaMeter(IReadOnlyList<MetricInstrumentClass> metricInstrumentClasses, CancellationToken cancellationToken)
            {
                var sb = GetStringBuilder();
                try
                {
                    _ = sb.Append("// <auto-generated/>\n");
                    _ = sb.Append("#nullable enable\n");
                    _ = sb.Append("    using Microsoft.Cloud.InstrumentationFramework.Metrics.Extensions;\n");
                    _ = sb.Append("    using Microsoft.R9.Extensions.Meter;\n");
                    _ = sb.Append("    using Microsoft.R9.Extensions.Meter.Geneva;\n");
                    _ = sb.Append("    using System.Collections.Concurrent;\n");

                    foreach (var metricInstrumentClass in metricInstrumentClasses)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        _ = sb.Append(GenMetricInstrumentFactory(metricInstrumentClass));
                    }

                    return sb.ToString();
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            public string EmitMetricInstruments(IReadOnlyList<MetricInstrumentClass> metricInstrumentClasses, CancellationToken cancellationToken)
            {
                var sb = GetStringBuilder();
                try
                {
                    _ = sb.Append("// <auto-generated/>\n");
                    _ = sb.Append("#nullable enable\n");

                    foreach (var metricInstrumentClass in metricInstrumentClasses)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        _ = sb.Append(GenType(metricInstrumentClass));
                    }

                    return sb.ToString();
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            private static string GetDimensionsValueType(MetricInstrumentMethod metricInstrumentMethod)
            {
                int count = metricInstrumentMethod.StaticDimensions.Count + metricInstrumentMethod.DynamicDimensions.Count;
                return $"DimensionValues{count}D";
            }

            private string GenType(MetricInstrumentClass metricInstrumentClass)
            {
                var sb = GetStringBuilder();
                try
                {
                    _ = sb.Append(GenCounterCreateMethods(metricInstrumentClass));

                    foreach (var metricInstrumentMethod in metricInstrumentClass.Methods)
                    {
                        _ = sb.Append(GenCounterClass(metricInstrumentMethod));
                    }

                    if (string.IsNullOrWhiteSpace(metricInstrumentClass.Namespace))
                    {
                        return $@"
    using System;
    using System.Collections.Generic;
    using Microsoft.Cloud.InstrumentationFramework.Metrics.Extensions;
    using Microsoft.R9.Extensions.Meter;
    using Microsoft.R9.Extensions.Meter.Geneva;

    {sb}
    ";
                    }

                    return $@"
    using System;
    using System.Collections.Generic;
    using Microsoft.Cloud.InstrumentationFramework.Metrics.Extensions;
    using Microsoft.R9.Extensions.Meter;
    using Microsoft.R9.Extensions.Meter.Geneva;

    namespace {metricInstrumentClass.Namespace}
    {{
        {sb}
    }}
    ";
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            private string GenMetricInstrumentFactory(MetricInstrumentClass metricInstrumentClass)
            {
                var sb = GetStringBuilder();
                try
                {
                    foreach (var metricInstrumentMethod in metricInstrumentClass.Methods)
                    {
                        _ = sb.Append(GenMetricInstrumentFactoryMethods(metricInstrumentMethod));
                    }

                    string str = $@"
        [global::System.Runtime.CompilerServices.CompilerGenerated]
        public static partial class GeneratedCounterMetricFactory
        {{
            private static readonly ConcurrentDictionary<string, ICounterMetric<long>> _longCounterMetrics = new ();
            private static readonly ConcurrentDictionary<string, IValueRecorderMetric<long>> _longValueRecorderMetrics = new ();
            {sb}
        }}
    ";
                    if (string.IsNullOrWhiteSpace(metricInstrumentClass.Namespace))
                    {
                        return str;
                    }

                    return $@"
    namespace {metricInstrumentClass.Namespace}
    {{
        {str}
    }}
    ";
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            private string GenMetricInstrumentFactoryMethods(MetricInstrumentMethod metricInstrumentMethod)
            {
                var meterParam = metricInstrumentMethod.AllParameters[0];

                if (metricInstrumentMethod.InstrumentType == InstrumentType.Counter)
                {
                    return $@"
            [global::System.Runtime.CompilerServices.CompilerGenerated]
            public static {metricInstrumentMethod.MetricName} Create{metricInstrumentMethod.MetricName}({meterParam.Type} {meterParam.Name}{GenStaticParameters(metricInstrumentMethod)})
            {{
                string metricName = ""{metricInstrumentMethod.MetricName}"";
                if (_longCounterMetrics.TryGetValue(metricName, out var counterMetric))
                {{
                    return (counterMetric as {metricInstrumentMethod.MetricName})!;
                }}

                GenevaMeter genevaMeter = (meter as GenevaMeter)!;

                var metric = _longCounterMetrics.GetOrAdd(metricName, (key) => {{
                    var cumulativeMetric = genevaMeter.MdmMetricFactory.CreateUInt64CumulativeMetric(
                                                MdmMetricFlags.CumulativeMetricDefault,
                                                genevaMeter.MonitoringAccount,
                                                genevaMeter.MetricNamespace,
                                                metricName
                                                {GenStaticParametersNames(metricInstrumentMethod)}
                                                {GenDynamicParametersNames(metricInstrumentMethod)});

                    return new {metricInstrumentMethod.MetricName}(cumulativeMetric{GenStaticParameters(metricInstrumentMethod, false)});
                }});

                return (metric as {metricInstrumentMethod.MetricName})!;
            }}
";
                }
                else if (metricInstrumentMethod.InstrumentType == InstrumentType.ValueRecorder)
                {
                    return $@"
            [global::System.Runtime.CompilerServices.CompilerGenerated]
            public static {metricInstrumentMethod.MetricName} Create{metricInstrumentMethod.MetricName}({meterParam.Type} {meterParam.Name}{GenStaticParameters(metricInstrumentMethod)})
            {{
                string metricName = ""{metricInstrumentMethod.MetricName}"";
                if (_longValueRecorderMetrics.TryGetValue(metricName, out var valueRecorderMetric))
                {{
                    return (valueRecorderMetric as {metricInstrumentMethod.MetricName})!;
                }}

                GenevaMeter genevaMeter = (meter as GenevaMeter)!;

                var metric = _longValueRecorderMetrics.GetOrAdd(metricName, (key) => {{
                    var cumulativeMetric = genevaMeter.MdmMetricFactory.CreateUInt64CumulativeMetric(
                                                MdmMetricFlags.CumulativeMetricDefault,
                                                genevaMeter.MonitoringAccount,
                                                genevaMeter.MetricNamespace,
                                                metricName
                                                {GenStaticParametersNames(metricInstrumentMethod)}
                                                {GenDynamicParametersNames(metricInstrumentMethod)});

                    return new {metricInstrumentMethod.MetricName}(cumulativeMetric{GenStaticParameters(metricInstrumentMethod, false)});
                }});

                return (metric as {metricInstrumentMethod.MetricName})!;
            }}
";
                }

                return $@"
                throw new ArgumentException()";
            }

            private string GenCounterCreateMethods(MetricInstrumentClass metricInstrumentClass)
            {
                var sb = GetStringBuilder();
                try
                {
                    foreach (var metricInstrumentMethod in metricInstrumentClass.Methods)
                    {
                        _ = sb.Append(GenCounterMethod(metricInstrumentMethod));
                    }

                    return $@"
        [global::System.Runtime.CompilerServices.CompilerGenerated]
        public static partial class {metricInstrumentClass.Name} {metricInstrumentClass.Constraints}
        {{
            {sb}
        }}
        ";
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            private string GenCounterClass(MetricInstrumentMethod metricInstrumentMethod)
            {
                string interfaceName = (metricInstrumentMethod.InstrumentType == InstrumentType.Counter) ? "ICounterMetric<long>" : "IValueRecorderMetric<long>";
                return $@"
        [global::System.Runtime.CompilerServices.CompilerGenerated]
        public partial class {metricInstrumentMethod.MetricName} : {interfaceName}
        {{
            private string[] _staticKeyArray;
            private string[] _staticValArray;
            private string[] _dynamicKeyArray;
            private string[] _dynamicValArray;            

            private {GetDimensionsValueType(metricInstrumentMethod)} _defaultDimensionValues;
            private bool _isDirty = true;

            internal IMdmCumulativeMetric<{GetDimensionsValueType(metricInstrumentMethod)}, ulong> CumulativeMetric {{ get; }}

            public {metricInstrumentMethod.MetricName}
                (IMdmCumulativeMetric<{GetDimensionsValueType(metricInstrumentMethod)}, ulong> cumulativeMetric 
                {GenStaticParameters(metricInstrumentMethod)})
            {{
                CumulativeMetric = cumulativeMetric ?? throw new ArgumentNullException(nameof(cumulativeMetric));
                _staticKeyArray = new string[{metricInstrumentMethod.StaticDimensions.Count}]; 
                _staticValArray = new string[{metricInstrumentMethod.StaticDimensions.Count}];

                _dynamicKeyArray = new string[{metricInstrumentMethod.DynamicDimensions.Count}];  
                _dynamicValArray = new string[{metricInstrumentMethod.DynamicDimensions.Count}];

                {GenConstructorBody(metricInstrumentMethod)}
            }}
            {GenClassProperties(metricInstrumentMethod)}
            {GenClassMethods(metricInstrumentMethod)}
        }}
        ";
            }

            private string GenCounterMethod(MetricInstrumentMethod metricInstrumentMethod)
            {
                string meterArg = _fieldName;
                foreach (var p in metricInstrumentMethod.AllParameters)
                {
                    if (p.IsMeter)
                    {
                        meterArg = p.Name;
                        break;
                    }
                }

                return $@"
            [global::System.Runtime.CompilerServices.CompilerGenerated]
            public static partial {metricInstrumentMethod.InstrumentClassType} {metricInstrumentMethod.Name}({GenParameters(metricInstrumentMethod)})
            {{
                return GeneratedCounterMetricFactory.Create{metricInstrumentMethod.MetricName}({meterArg}{GenStaticParameters(metricInstrumentMethod, false)});
            }}
            ";
            }

            private string GenParameters(MetricInstrumentMethod metricInstrumentMethod, bool includeType = true)
            {
                var sb = GetStringBuilder();
                try
                {
                    foreach (var p in metricInstrumentMethod.AllParameters)
                    {
                        if (p != metricInstrumentMethod.AllParameters[0])
                        {
                            _ = sb.Append(", ");
                        }

                        if (includeType)
                        {
                            _ = sb.Append($"{p.Type} {p.Name}");
                        }
                        else
                        {
                            _ = sb.Append($"{p.Name}");
                        }
                    }

                    return sb.ToString();
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            private string GenRegularParameters(MetricInstrumentMethod metricInstrumentMethod, bool includeType = true)
            {
                var sb = GetStringBuilder();
                try
                {
                    foreach (var p in metricInstrumentMethod.RegularParameters)
                    {
                        if (p != metricInstrumentMethod.RegularParameters[0])
                        {
                            _ = sb.Append(", ");
                        }

                        if (includeType)
                        {
                            _ = sb.Append($"{p.Type} {p.Name}");
                        }
                        else
                        {
                            _ = sb.Append($"{p.Name}");
                        }
                    }

                    return sb.ToString();
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            private string GenRegularParametersNames(MetricInstrumentMethod metricInstrumentMethod)
            {
                var sb = GetStringBuilder();
                try
                {
                    foreach (var p in metricInstrumentMethod.RegularParameters)
                    {
                        if (p != metricInstrumentMethod.RegularParameters[0])
                        {
                            _ = sb.Append(", ");
                        }

                        _ = sb.Append($"nameof({p.Name})");
                    }

                    return sb.ToString();
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            private string GenStaticParameters(MetricInstrumentMethod metricInstrumentMethod, bool includeType = true)
            {
                var sb = GetStringBuilder();
                try
                {
                    foreach (var dimension in metricInstrumentMethod.StaticDimensions)
                    {
                        _ = sb.Append(", ");

                        if (includeType)
                        {
                            _ = sb.Append($"string ");
                        }

                        _ = sb.Append($"{dimension}");
                    }

                    return sb.ToString();
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            private string GenDynamicParameters(MetricInstrumentMethod metricInstrumentMethod, bool includeType = true)
            {
                var sb = GetStringBuilder();
                try
                {
                    foreach (var dimension in metricInstrumentMethod.DynamicDimensions)
                    {
                        _ = sb.Append(", ");

                        if (includeType)
                        {
                            _ = sb.Append($"string ");
                        }

                        _ = sb.Append($"{dimension}");
                    }

                    return sb.ToString();
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            private string GenStaticParametersNames(MetricInstrumentMethod metricInstrumentMethod)
            {
                var sb = GetStringBuilder();
                try
                {
                    foreach (var dimension in metricInstrumentMethod.StaticDimensions)
                    {
                        _ = sb.Append(@$", ""{dimension}""");
                    }

                    return sb.ToString();
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            private string GenDynamicParametersNames(MetricInstrumentMethod metricInstrumentMethod)
            {
                var sb = GetStringBuilder();
                try
                {
                    foreach (var dimension in metricInstrumentMethod.DynamicDimensions)
                    {
                        _ = sb.Append(@$", ""{dimension}""");
                    }

                    return sb.ToString();
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            private string GenConstructorBody(MetricInstrumentMethod metricInstrumentMethod)
            {
                var sb = GetStringBuilder();
                try
                {
                    int index = 0;
                    foreach (var staticDimension in metricInstrumentMethod.StaticDimensions)
                    {
                        _ = sb.Append($@"
                _staticKeyArray[{index}] = ""{staticDimension}"";
                _staticValArray[{index}] = {staticDimension};");

                        index++;
                    }

                    index = 0;
                    foreach (var dynamicDimension in metricInstrumentMethod.DynamicDimensions)
                    {
                        _ = sb.Append($@"

                _dynamicKeyArray[{index}] = ""{dynamicDimension}"";");

                        index++;
                    }

                    return sb.ToString();
                }
                finally
                {
                    ReturnStringBuilder(sb);
                }
            }

            private string GenClassProperties(MetricInstrumentMethod metricInstrumentMethod)
            {
                var sb = GetStringBuilder();
                var subsb = GetStringBuilder();
                try
                {
                    int index = 0;
                    foreach (var dimension in metricInstrumentMethod.DynamicDimensions)
                    {
                        _ = sb.Append($@"
            private string {dimension}
            {{
                get => _dynamicValArray[{index}];
                set {{ if (_dynamicValArray[{index}] != value) {{ _dynamicValArray[{index}] = value; _isDirty = true; }} }}
            }}");

                        index++;
                    }

                    return sb.ToString();
                }
                finally
                {
                    ReturnStringBuilder(subsb);
                    ReturnStringBuilder(sb);
                }
            }

            private string GenClassMethods(MetricInstrumentMethod metricInstrumentMethod)
            {
                var sb = GetStringBuilder();
                var subsb = GetStringBuilder();
                try
                {
                    int i = 0;
                    for (; i < metricInstrumentMethod.StaticDimensions.Count; i++)
                    {
                        if (i > 0)
                        {
                            _ = sb.Append(", ");
                        }

                        _ = sb.Append($"_staticValArray[{i}]");
                    }

                    for (i = 0; i < metricInstrumentMethod.DynamicDimensions.Count; i++)
                    {
                        if (i > 0 || metricInstrumentMethod.StaticDimensions.Count > 0)
                        {
                            _ = sb.Append(", ");
                        }

                        _ = sb.Append($"_dynamicValArray[{i}]");
                    }

                    foreach (var dimension in metricInstrumentMethod.DynamicDimensions)
                    {
                        _ = subsb.Append($@"
                    this.{dimension} = {dimension};");
                    }

                    string methodName = metricInstrumentMethod.InstrumentType == InstrumentType.Counter ? "Add" : "Record";

                    string commulativeOperation = metricInstrumentMethod.InstrumentType == InstrumentType.Counter ?
                        $@"_ = value > 0
                            ? CumulativeMetric.IncrementBy((ulong)value, _defaultDimensionValues)
                            : CumulativeMetric.DecrementBy((ulong)value, _defaultDimensionValues);
                        " :
                        $@"_ = CumulativeMetric.Set((ulong)value, _defaultDimensionValues);
                        ";

                    string str = string.Empty;
                    if (metricInstrumentMethod.DynamicDimensions.Count > 0)
                    {
                        str = $@"
            public void {methodName}(long value{GenDynamicParameters(metricInstrumentMethod)})
            {{
                if (value != 0)
                {{
                    {subsb}
                    if (_isDirty)
                    {{
                        _defaultDimensionValues = DimensionValues.Create({sb});
                        _isDirty = false;
                    }}

                    {commulativeOperation}
                }}
            }}";
                    }

                    return $@"{str}

            public void {methodName}(long value, IList<(string key, string value)>? dimensions)
            {{
                throw new NotImplementedException();
            }}
            ";
                }
                finally
                {
                    ReturnStringBuilder(subsb);
                    ReturnStringBuilder(sb);
                }
            }

            private StringBuilder GetStringBuilder()
            {
                const int DefaultStringBuilderCapacity = 1024;

                if (_builders.Count == 0)
                {
                    return new StringBuilder(DefaultStringBuilderCapacity);
                }

                var sb = _builders.Pop();
                _ = sb.Clear();
                return sb;
            }

            private void ReturnStringBuilder(StringBuilder sb)
            {
                _builders.Push(sb);
            }
        }
    }
}
