//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.R9.Generators.Metric {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.R9.Generators.Metric.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter names conflicts with the dynamic dimensions in the attribute arguments.
        /// </summary>
        internal static string ErrorConflictingDimensionMessage {
            get {
                return ResourceManager.GetString("ErrorConflictingDimensionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter names conflicts with the dynamic dimensions in the attribute arguments.
        /// </summary>
        internal static string ErrorConflictingDimensionTitle {
            get {
                return ResourceManager.GetString("ErrorConflictingDimensionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension names should contain alphanumeric characters and only allowed symbols.
        /// </summary>
        internal static string ErrorInvalidDimensionNamesMessage {
            get {
                return ResourceManager.GetString("ErrorInvalidDimensionNamesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension names should contain alphanumeric characters and only allowed symbols.
        /// </summary>
        internal static string ErrorInvalidDimensionNamesTitle {
            get {
                return ResourceManager.GetString("ErrorInvalidDimensionNamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric method names cannot start with _.
        /// </summary>
        internal static string ErrorInvalidMethodNameMessage {
            get {
                return ResourceManager.GetString("ErrorInvalidMethodNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric method names cannot start with _.
        /// </summary>
        internal static string ErrorInvalidMethodNameTitle {
            get {
                return ResourceManager.GetString("ErrorInvalidMethodNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric methods must return {0} type.
        /// </summary>
        internal static string ErrorInvalidMethodReturnTypeMessage {
            get {
                return ResourceManager.GetString("ErrorInvalidMethodReturnTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric methods must return strong type.
        /// </summary>
        internal static string ErrorInvalidMethodReturnTypeTitle {
            get {
                return ResourceManager.GetString("ErrorInvalidMethodReturnTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric name {0} is invalid. It must be non empty and start with an alphabetic character.
        /// </summary>
        internal static string ErrorInvalidMetricNameMessage {
            get {
                return ResourceManager.GetString("ErrorInvalidMetricNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric name must be non empty and start with an alphabetic character.
        /// </summary>
        internal static string ErrorInvalidMetricNameTitle {
            get {
                return ResourceManager.GetString("ErrorInvalidMetricNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric method parameter names cannot start with _.
        /// </summary>
        internal static string ErrorInvalidParameterNameMessage {
            get {
                return ResourceManager.GetString("ErrorInvalidParameterNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric method parameter names cannot start with _.
        /// </summary>
        internal static string ErrorInvalidParameterNameTitle {
            get {
                return ResourceManager.GetString("ErrorInvalidParameterNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric methods cannot have a body.
        /// </summary>
        internal static string ErrorMethodHasBodyMessage {
            get {
                return ResourceManager.GetString("ErrorMethodHasBodyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric methods cannot have a body.
        /// </summary>
        internal static string ErrorMethodHasBodyTitle {
            get {
                return ResourceManager.GetString("ErrorMethodHasBodyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric methods cannot be generic.
        /// </summary>
        internal static string ErrorMethodIsGenericMessage {
            get {
                return ResourceManager.GetString("ErrorMethodIsGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric methods cannot be generic.
        /// </summary>
        internal static string ErrorMethodIsGenericTitle {
            get {
                return ResourceManager.GetString("ErrorMethodIsGenericTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple metric instrument methods are using metric name {0}.
        /// </summary>
        internal static string ErrorMetricNameReuseMessage {
            get {
                return ResourceManager.GetString("ErrorMetricNameReuseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple metric methods cannot use the same metric name.
        /// </summary>
        internal static string ErrorMetricNameReuseTitle {
            get {
                return ResourceManager.GetString("ErrorMetricNameReuseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each key in StaticDimension argument should have corresponding parameter.
        /// </summary>
        internal static string ErrorMismatchingStaticDimensionsCountMessage {
            get {
                return ResourceManager.GetString("ErrorMismatchingStaticDimensionsCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each key in StaticDimension argument should have corresponding parameter.
        /// </summary>
        internal static string ErrorMismatchingStaticDimensionsCountTitle {
            get {
                return ResourceManager.GetString("ErrorMismatchingStaticDimensionsCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First parameter should be of Microsoft.R9.Extensions.Meter.IMeter type.
        /// </summary>
        internal static string ErrorMissingMeterMessage {
            get {
                return ResourceManager.GetString("ErrorMissingMeterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First parameter should be of Microsoft.R9.Extensions.Meter.IMeter type.
        /// </summary>
        internal static string ErrorMissingMeterTitle {
            get {
                return ResourceManager.GetString("ErrorMissingMeterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric class cannot be in nested types.
        /// </summary>
        internal static string ErrorNestedTypeMessage {
            get {
                return ResourceManager.GetString("ErrorNestedTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric class cannot be in nested types.
        /// </summary>
        internal static string ErrorNestedTypeTitle {
            get {
                return ResourceManager.GetString("ErrorNestedTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric methods must be partial.
        /// </summary>
        internal static string ErrorNotPartialMethodMessage {
            get {
                return ResourceManager.GetString("ErrorNotPartialMethodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric methods must be partial.
        /// </summary>
        internal static string ErrorNotPartialMethodTitle {
            get {
                return ResourceManager.GetString("ErrorNotPartialMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric methods must be static.
        /// </summary>
        internal static string ErrorNotStaticMethodMessage {
            get {
                return ResourceManager.GetString("ErrorNotStaticMethodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric methods must be static.
        /// </summary>
        internal static string ErrorNotStaticMethodTitle {
            get {
                return ResourceManager.GetString("ErrorNotStaticMethodTitle", resourceCulture);
            }
        }
    }
}
